#!/bin/bash
#
# Mac mini 上で Claude Code の Remote Control サーバーを常駐させるセットアップ。
# iPhone / claude.ai から「常にそこに居るセッション」に接続できる状態を作る。
#
#   使い方:  bash claude-rc-setup.sh
#   作業対象を変える場合:  PROJECT_DIR=/Volumes/T7/別のフォルダ bash claude-rc-setup.sh
#
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-/Volumes/T7/MASTER}"
VOLUME_ROOT="/Volumes/T7"
SESSION_NAME="${SESSION_NAME:-MacMini-T7}"
LABEL="com.pawtner.claude-rc"
WRAPPER="$HOME/bin/claude-rc.sh"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
die() { printf '\n\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------- 事前チェック
say "環境を確認しています"

[ "$(uname -s)" = "Darwin" ] || die "このスクリプトは macOS 上で実行してください。"

CLAUDE_BIN="$(command -v claude || true)"
[ -n "$CLAUDE_BIN" ] || die "claude コマンドが見つかりません。Claude Code CLI をインストールして PATH を通してください。"
echo "  claude : $CLAUDE_BIN"

NODE_DIR=""
if NODE_BIN="$(command -v node 2>/dev/null)"; then
  NODE_DIR="$(dirname "$NODE_BIN")"
  echo "  node   : $NODE_BIN"
fi

if [ ! -d "$PROJECT_DIR" ]; then
  die "$PROJECT_DIR が見つかりません。T7 がマウントされているか、PROJECT_DIR の指定を確認してください。"
fi
echo "  作業先 : $PROJECT_DIR"

# 信頼ダイアログを一度通しているか（未承認だと launchd 起動時に固まる）
if [ ! -f "$HOME/.claude.json" ] || ! grep -q "$PROJECT_DIR" "$HOME/.claude.json" 2>/dev/null; then
  cat <<MSG

  ⚠️  $PROJECT_DIR で claude をまだ一度も起動していないようです。
      launchd から起動すると信頼ダイアログに応答できず失敗するため、
      先に下記を一度だけ手で実行して「信頼する」を選び、終了してください。

          cd "$PROJECT_DIR" && claude

MSG
  read -r -p "  一度起動して承認済みなら Enter、これから行うなら Ctrl-C で中断: " _
fi

# ---------------------------------------------------------------- ラッパー生成
say "起動ラッパーを作成します: $WRAPPER"

# T7 が外れてもスクリプト自体は消えないよう、ホーム側に置く
mkdir -p "$HOME/bin" "$LOG_DIR"

cat > "$WRAPPER" <<WRAP
#!/bin/bash
# generated by claude-rc-setup.sh — 直接編集せず、スクリプトを再実行してください
export PATH="${NODE_DIR:+$NODE_DIR:}\$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

PROJECT_DIR="$PROJECT_DIR"
VOLUME_ROOT="$VOLUME_ROOT"

# T7 のマウントを最大 5 分待つ（起動直後・一時的なアンマウントからの復帰に対応）
for _ in \$(seq 1 60); do
  [ -d "\$PROJECT_DIR" ] && break
  sleep 5
done

if [ ! -d "\$PROJECT_DIR" ]; then
  echo "\$(date '+%F %T') \$VOLUME_ROOT がマウントされていないため起動を中止しました" >&2
  exit 1
fi

cd "\$PROJECT_DIR"
echo "\$(date '+%F %T') starting remote-control in \$PROJECT_DIR"
exec "$CLAUDE_BIN" remote-control --name "$SESSION_NAME"
WRAP

chmod +x "$WRAPPER"

# ---------------------------------------------------------------- LaunchAgent
say "LaunchAgent を作成します: $PLIST"

mkdir -p "$HOME/Library/LaunchAgents"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>$WRAPPER</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>30</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>$LOG_DIR/claude-rc.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/claude-rc.err</string>
</dict>
</plist>
PLIST_EOF

say "LaunchAgent を登録します"
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
launchctl kickstart -k "gui/$(id -u)/$LABEL"

# ---------------------------------------------------------------- 起動確認
say "起動を確認しています（15秒待機）"
sleep 15

if launchctl print "gui/$(id -u)/$LABEL" >/dev/null 2>&1; then
  echo "  ✅ LaunchAgent は登録されています"
else
  echo "  ⚠️  LaunchAgent が見つかりません。$LOG_DIR/claude-rc.err を確認してください"
fi

if pgrep -f "remote-control" >/dev/null 2>&1; then
  echo "  ✅ remote-control プロセスが動いています"
else
  echo "  ⚠️  プロセスが見つかりません。下記ログを確認してください:"
  echo "      tail -n 40 $LOG_DIR/claude-rc.err"
fi

# ---------------------------------------------------------------- 残りの案内
cat <<DONE

────────────────────────────────────────────────────────
 セットアップ完了。残りは手作業で 3 つだけです。
────────────────────────────────────────────────────────

 1) Mac mini をスリープさせない（要管理者パスワード）

      sudo pmset -a sleep 0 disksleep 0

    さらに システム設定 → 一般 → ログイン と 自動ログイン で
    「停電後に自動的に起動」と自動ログインを有効にしてください。
    （LaunchAgent はログイン後に走るため、これが無いと再起動後に復活しません）

 2) フルディスクアクセスを付与

    システム設定 → プライバシーとセキュリティ → フルディスクアクセス に
    ターミナル.app（および node）を追加。外部ボリュームの読み書きが
    TCC に弾かれる事故を防ぎます。

 3) iPhone への通知を有効化

    Mac mini の Claude Code セッション内で /config を開き、
      ・Push when Claude decides
      ・Push when actions required
    をオン。許可確認が iPhone に飛び、その場で承認できるようになります。

────────────────────────────────────────────────────────
 iPhone 側の使い方
────────────────────────────────────────────────────────

    Claude アプリ → 下部の [Code] タブ → "$SESSION_NAME"
    （PC アイコン + 緑のドット）をタップ

    このサーバーは同時に複数セッションを持てるので、
    iPhone 側から新しいセッションを追加で立ち上げることもできます。

────────────────────────────────────────────────────────
 運用コマンド
────────────────────────────────────────────────────────

    再起動   : launchctl kickstart -k gui/\$(id -u)/$LABEL
    停止     : launchctl bootout gui/\$(id -u)/$LABEL
    再登録   : launchctl bootstrap gui/\$(id -u) $PLIST
    ログ     : tail -f $LOG_DIR/claude-rc.err
    状態確認 : launchctl print gui/\$(id -u)/$LABEL | head -20

DONE
