#!/bin/bash
#
# Mac mini 上で Claude Code の Remote Control サーバーを常駐させるセットアップ。
# iPhone / claude.ai から「常にそこに居るセッション」に接続できる状態を作る。
#
#   使い方:
#     curl -fsSL https://raw.githubusercontent.com/pawtner-official/pawtner-reports/claude/t7-unmount-incident-6rtkb9/tools/claude-rc-setup.sh -o /tmp/claude-rc-setup.sh
#     bash /tmp/claude-rc-setup.sh
#
#   作業対象を変える場合:
#     PROJECT_DIR=/Volumes/T7/別フォルダ bash /tmp/claude-rc-setup.sh
#
set -uo pipefail

PROJECT_DIR="${PROJECT_DIR:-/Volumes/T7/MASTER}"
VOLUME_ROOT="${VOLUME_ROOT:-/Volumes/T7}"
SESSION_NAME="${SESSION_NAME:-MacMini-T7}"
LABEL="com.pawtner.claude-rc"
WRAPPER="$HOME/bin/claude-rc.sh"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs"
UID_NUM="$(id -u)"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
ok()   { printf '    \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '    \033[33m!\033[0m %s\n' "$1"; }
die()  { printf '\n\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

# ============================================================ 1. 事前チェック
say "環境を確認しています"

[ "$(uname -s)" = "Darwin" ] || die "このスクリプトは macOS 上で実行してください。"

CLAUDE_BIN="$(command -v claude || true)"
[ -n "$CLAUDE_BIN" ] || die "claude コマンドが見つかりません。Claude Code CLI を入れて PATH を通してください。"
ok "claude: $CLAUDE_BIN"

NODE_DIR=""
NODE_BIN="$(command -v node 2>/dev/null || true)"
if [ -n "$NODE_BIN" ]; then
  NODE_DIR="$(dirname "$NODE_BIN")"
  ok "node: $NODE_BIN"
fi

[ -d "$PROJECT_DIR" ] || die "$PROJECT_DIR が見つかりません。T7 がマウントされているか確認してください。"
ok "作業先: $PROJECT_DIR"

# ============================================ 2. 信頼ダイアログ（対話が必要）
# 未承認のまま launchd から起動するとダイアログに応答できず失敗するため、
# ここで一度だけ対話的に起動して通しておく。
if grep -q "\"$PROJECT_DIR\"" "$HOME/.claude.json" 2>/dev/null; then
  say "信頼ダイアログ: 承認済みです"
else
  say "信頼ダイアログを通します（この 1 回だけ対話が必要です）"
  cat <<'MSG'
    これから claude を起動します。
      1. 「Yes, I trust this folder」を選択
      2. 起動したら /exit で終了
    セットアップはその後自動で続行します。
MSG
  printf '    Enter で起動します... '
  read -r _ < /dev/tty || true
  ( cd "$PROJECT_DIR" && "$CLAUDE_BIN" ) < /dev/tty || true
fi

# ============================================================ 3. ラッパー生成
say "起動ラッパーを作成します: $WRAPPER"

# T7 が外れてもスクリプト自体は消えないよう、ホーム側に置く
mkdir -p "$HOME/bin" "$LOG_DIR"

cat > "$WRAPPER" <<WRAP
#!/bin/bash
# generated by claude-rc-setup.sh — 直接編集せず、セットアップを再実行してください
export PATH="${NODE_DIR:+$NODE_DIR:}\$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

PROJECT_DIR="$PROJECT_DIR"
VOLUME_ROOT="$VOLUME_ROOT"

# T7 のマウントを最大 5 分待つ（起動直後・一時的なアンマウントからの復帰に対応）
for _ in \$(seq 1 60); do
  [ -d "\$PROJECT_DIR" ] && break
  sleep 5
done

if [ ! -d "\$PROJECT_DIR" ]; then
  echo "\$(date '+%F %T') \$VOLUME_ROOT が未マウントのため起動を中止しました" >&2
  exit 1
fi

cd "\$PROJECT_DIR"
echo "\$(date '+%F %T') starting remote-control in \$PROJECT_DIR"
exec "$CLAUDE_BIN" remote-control --name "$SESSION_NAME"
WRAP

chmod +x "$WRAPPER"
ok "作成しました"

# ========================================================= 4. LaunchAgent 登録
say "LaunchAgent を登録します: $LABEL"

mkdir -p "$HOME/Library/LaunchAgents"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>$WRAPPER</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>30</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>$LOG_DIR/claude-rc.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/claude-rc.err</string>
</dict>
</plist>
PLIST_EOF

launchctl bootout "gui/$UID_NUM/$LABEL" 2>/dev/null || true
if launchctl bootstrap "gui/$UID_NUM" "$PLIST" 2>/dev/null; then
  ok "登録しました"
else
  warn "bootstrap に失敗しました。ログを確認してください"
fi
launchctl kickstart -k "gui/$UID_NUM/$LABEL" 2>/dev/null || true

# ================================================== 5. 電源設定（自動化できる分）
say "電源設定を適用します（管理者パスワードを求められます）"
if sudo -v 2>/dev/null; then
  sudo pmset -a sleep 0 disksleep 0 >/dev/null 2>&1 && ok "スリープ・ディスクスリープを無効化"
  sudo pmset -a autorestart 1      >/dev/null 2>&1 && ok "停電復帰後の自動起動を有効化"
  sudo pmset -a womp 1             >/dev/null 2>&1 && ok "ネットワークアクセスによるスリープ解除を有効化"
else
  warn "sudo をスキップしました。後で手動で実行してください:"
  echo "        sudo pmset -a sleep 0 disksleep 0 autorestart 1 womp 1"
fi

# ============================================================== 6. 起動確認
say "起動を確認しています（20 秒待機）"
sleep 20

RC_OK=0
if pgrep -f "remote-control --name $SESSION_NAME" >/dev/null 2>&1; then
  ok "remote-control プロセスが稼働中です"
  RC_OK=1
else
  warn "プロセスが見つかりません"
fi

SESSION_URL="$(grep -Eo 'https://claude\.ai/code/[A-Za-z0-9_-]+' "$LOG_DIR/claude-rc.log" 2>/dev/null | tail -1)"
[ -n "$SESSION_URL" ] && ok "セッション URL: $SESSION_URL"

if [ "$RC_OK" -eq 0 ]; then
  echo
  echo "--- 直近のログ ---"
  tail -n 25 "$LOG_DIR/claude-rc.err" 2>/dev/null
  tail -n 25 "$LOG_DIR/claude-rc.log" 2>/dev/null
  echo "------------------"
fi

# ======================================== 7. GUI 設定パネルを開く（自動化不可分）
say "手動設定が必要なパネルを開きます"
open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null \
  && ok "フルディスクアクセスのパネルを開きました" \
  || warn "システム設定 → プライバシーとセキュリティ → フルディスクアクセス を手で開いてください"

# ================================================================== 完了案内
cat <<DONE

────────────────────────────────────────────────────────
 自動設定はここまでで完了です
────────────────────────────────────────────────────────

 残りの手作業（自動化できない GUI 設定）は 2 つだけです。

 1) フルディスクアクセス  ※パネルは今開いています
    ターミナル.app を追加してオンにしてください。
    外部ボリューム（T7）の読み書きが TCC に弾かれる事故を防ぎます。

 2) 自動ログイン
    システム設定 → ユーザとグループ → 自動ログイン を有効化。
    LaunchAgent はログイン後に走るため、これが無いと
    Mac mini 再起動後に復活しません。

 （任意）iPhone への通知
    iPhone から開いたセッション内で /config を実行し、
    Push when Claude decides / Push when actions required をオン。

────────────────────────────────────────────────────────
 iPhone からの使い方
────────────────────────────────────────────────────────

    Claude アプリ → [Code] タブ → "$SESSION_NAME"
    （PC アイコン + 緑のドット）をタップ

    ⚠️ 「新規タスク」から作ると Cloud セッションになり
       T7 に届きません。必ず一覧から開いてください。

────────────────────────────────────────────────────────
 運用コマンド
────────────────────────────────────────────────────────

    再起動 : launchctl kickstart -k gui/$UID_NUM/$LABEL
    停止   : launchctl bootout   gui/$UID_NUM/$LABEL
    ログ   : tail -f $LOG_DIR/claude-rc.err
    状態   : launchctl print gui/$UID_NUM/$LABEL | head -20

DONE
